_BASE_: ../segmentation_base.yaml

OUTPUT_DIR: ./output/region

NAME: photo

PREPROCESS:
  REGION:
    REGIONS: ["Photo"]
    MERGE_REGIONS: []
    REGION_TYPE: ["ImageRegion:Photo"]
    RECTANGLE_REGIONS: ["Photo"]
    MIN_REGION_SIZE: 10

MODEL:
  MODE: region

  SEM_SEG_HEAD:
    NUM_CLASSES: 2

  ROI_HEADS:
    NUM_CLASSES: 1

  WEIGHTS:

INPUT:
  GRAYSCALE:
    PROBABILITY: 0.1

  BRIGHTNESS:
    PROBABILITY: 0.3
    MIN_INTENSITY: 0.5
    MAX_INTENSITY: 1.5

  CONTRAST:
    PROBABILITY: 0.3
    MIN_INTENSITY: 0.5
    MAX_INTENSITY: 1.5

  SATURATION:
    PROBABILITY: 0.3
    MIN_INTENSITY: 0.5
    MAX_INTENSITY: 1.5

  GAUSSIAN_FILTER:
    PROBABILITY: 0.3
    MIN_SIGMA: 0.5
    MAX_SIGMA: 1.5

  HORIZONTAL_FLIP:
    PROBABILITY: 0.2

  VERTICAL_FLIP:
    PROBABILITY: 0.2

  ELASTIC_DEFORMATION:
    PROBABILITY: 0.3
    ALPHA: 0.1
    SIGMA: 0.01

  AFFINE:
    PROBABILITY: 1.

    TRANSLATION:
      PROBABILITY: 0.9
      STANDARD_DEVIATION: 0.02

    ROTATION:
      PROBABILITY: 0.9
      KAPPA: 30.

    SHEAR:
      PROBABILITY: 0.9
      KAPPA: 20.

    SCALE:
      PROBABILITY: 0.9
      STANDARD_DEVIATION: 0.12

TRAIN:
  WEIGHTS:

TEST:
  WEIGHTS:
  EVAL_PERIOD: 10000

SOLVER:
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 25000
  BASE_LR: 0.0002
  GAMMA: 0.1
  STEPS: () #(80000, 120000, 160000)
  MAX_ITER: 250000
