_BASE_: ../segmentation_base.yaml

OUTPUT_DIR: ./output/region

NAME: rekesten_v3a

PREPROCESS:
  REGION:
    REGIONS:
      [
        "Text",
        "request",
        "addressing",
        "metadata\\u0020request",
        "appendix",
        "metadata\\u0020cover",
        "petitioner",
        "signature-mark",
        "date",
        "marginalia",
      ]
    MERGE_REGIONS: ["metadata\\u0020request:marginalia"]
    REGION_TYPE: []

MODEL:
  MODE: region

  SEM_SEG_HEAD:
    NUM_CLASSES: 10

  ROI_HEADS:
    NUM_CLASSES: 9

  WEIGHTS:

DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False

TRAIN:
  WEIGHTS:

TEST:
  WEIGHTS: pretrained_models/region_model_best_mIoU.pth
